created sign up ui
BeforeTheEnd-Inc/Bucketful pull request #23
Opened 2018-04-29 17:29 UTC by djpara

2018-05-01 05:30 UTC, djpara commented
Removed comments and TODO: markers. UI implemented with Bootstrap. Will need to refactor styling everywhere else in the app. Need to complete database save. Coordinating with Mark on that

2018-05-02 02:11 UTC, alredi requested changes

2018-05-02 02:11 UTC, alredi commented on imports/api/profiles.js
> +        allowedValues: ['Not started', 'Travel', 'Entertainment', 'Sports']
These are categories, not countries. If we're only allowing states right now, let's not worry about a country?

2018-05-02 02:11 UTC, alredi commented on imports/api/profiles.js
> +        allowedValues: ['Female', 'Male'],
Let's add an option for 'Undisclosed'

2018-05-02 02:11 UTC, alredi commented on imports/api/profiles.js
> +
Why are we allowing and denying the same functions? (lines 7-19 vs. lines 21-33)

2018-05-04 14:04 UTC, alredi approved these changes

2018-05-04 14:11 UTC, merged